## 배포 용

server:
  port: 2000

spring:
  # Redis 설정
  redis:
    host: ${redis.host}
    port: ${redis.port}

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB

  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:1521:xe
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddlAuto: create

  # 타임리프 설정
  thymeleaf:
    cache: true
    prefix: classpath:/templates/

  jackson:
    serialization:
      fail-on-empty-beans: false

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# 파일 업로드 경로 설정
file:
  upload:
    path: /home/project/uploads/    # (임시)변경 가능
    url: /uploads/